### ISSUE TITLE
display more texts

### ISSUE THREAD

**Issue by longnguyen1981** [David-Desmaisons/Vue.D3.tree#10]
Hi David, thanks a lot for your excellent work. I built a parse tree and it was beautiful. However, I can not display more texts. For example, I have a data like this: 
```
tree: {
        name: 'father',
        age: '70',
        children: [{
          name: 'son1',
          age: '50',
          children: [{name: 'grandson', age: '20'}, {name: 'grandson2', age: '21'}]
        }, {
          name: 'son2',
          age: '49',
          children: [{name: 'grandson3', age: '22'}, {name: 'grandson4', age: '23'}]
        }]
     }
```
, and I want to display not only 'name' but also 'age' as nodeText. It is not possible. Could you provide me a solution? It would be greatly appriciate.

**Comment by David-Desmaisons** [comment]
Hi @hoanglong2k , well you can "process" your original data to concatenate name and age before using the component.

**Comment by hoanglong2k** [comment]
Hi David, thanks for the response. I have dicked a little bit into your code. Of course, I could process data to concat the name but I could see that we can give the flexibility to append text. 
At the moment you fix it by: 
```
const text = allNodes.append('text')
        .attr('dy', '.35em')
        .text(d => d.data[this.nodeText])
        .style('fill', 'blue')
        .on('click', d => {
          currentSelected = (currentSelected === d) ? null : d
          d3.event.stopPropagation()
          this.redraw()
          this.$emit('clicked', {element: d, data: d.data})
        })
```

**Comment by David-Desmaisons** [comment]
Use the "popUp" slot release in version v5.1.0.
