### ISSUE TITLE
This is a error. This nodeText's prop is not defined.

### ISSUE THREAD

**Issue by IsSwm** [David-Desmaisons/Vue.D3.tree#11]
I user news npm install.
I am look at ReadMe, this is nothing error to help me. Please check this error by my file.
MyFile by this http://47.100.21.2/My.vue
console error :   http://47.100.21.2/error.png

**Comment by David-Desmaisons** [comment]
```HTML
node-text="name" 
```
Or
```HTML
:node-text="'name'" 
```
