### ISSUE TITLE
Multiple parent nodes?

### ISSUE THREAD

**Issue by jakub-wisniewski** [David-Desmaisons/Vue.D3.tree#14]
Can I make a graph with more than one parent node using Vue D3 Tree?

**Comment by David-Desmaisons** [comment]
What do you mean? Can you share a sketch or a better description?

**Comment by jakub-wisniewski** [comment]
![graph](https://user-images.githubusercontent.com/25643661/35675920-23aa55d8-074a-11e8-96cf-c61b69437cd7.png)

**Comment by jakub-wisniewski** [comment]
?

**Comment by David-Desmaisons** [comment]
This is not supported. There is not such a layer provided by D3.js
