### ISSUE TITLE
Missing label text on one node only

### ISSUE THREAD

**Issue by curtisdelicata** [David-Desmaisons/Vue.D3.tree#17]
I have now got this to render and it looks nice but one node doesn't show the text. The other three do. Below is my code and attached is a link.

https://github.com/modularsoftware/genealogy/blob/master/resources/assets/js/pages/trees/Show.vue

**Comment by curtisdelicata** [comment]
> <template>
    <div id="tree">
        <tree class="tree" :identifier="getId" :node-text="text" :data="treeData" :duration=5 :margin-x=0 :margin-y=10></tree>
    </div>
</template>

<script>
import { tree } from 'vued3tree';

export default {
    components: {
        tree,
    },
    data() {
        return {
            text: 'text',
            treeData: {
                id: 1,
                text: 'father',
                children: [
                    {
                        id: 2,
                        text: 'son1',
                        children: [{ id: 4, text: 'grandson' }, { id: 5, text: 'grandson2' }],
                    },
                    {
                        id: 3,
                        text: 'son2',
                        children: [{ id: 6, name: 'grandson3' }, { id: 7, text: 'grandson4' }],
                    },
                ],
            },
        };
    },
    methods: {
        getId(node) {
            return node.id;
        },
    },
};
</script>
<style>
#tree {
    width: 100%;
    max-height: 600px;
    height: 600px;
}

#tree svg {
    margin-top: 32px;
    border: 1px solid #aaa;
    max-height: 600px;
}
</style>

**Comment by David-Desmaisons** [comment]
Nice project.
Try (whith sibgle quote):
`:node-text="'text'"
`Or
`node-text="text"`
Both should work

**Comment by curtisdelicata** [comment]
Thank you.

Same issue with either of your options. Grandson 3 does not display text.

**Comment by David-Desmaisons** [comment]
This is because grandson has not any text property instead it has a name....

name: 'grandson3'

**Comment by curtisdelicata** [comment]
Solved. Not sure how I missed that! Sorry about that. Thank you.
