### ISSUE TITLE
How to make the links data take effect in <tree></tree>

### ISSUE THREAD

**Issue by Aaron-Coding-Coding** [David-Desmaisons/Vue.D3.tree#18]
Hello, David.
Thanks for your nice tree.
i want to make more than one link for leaf nodes in <tree> component.
for example, b is a leaf node . root node a links b , root node c links b too. 
i tried to add links in data.json like:
links:[
{
     "source": a.id,
      "target": b.id,
       "value": 1
},
{
     "source": c.id,
      "target": b.id,
       "value": 1
}
]
but it didn't work, can you help me ? thanks for any suggestion

**Comment by David-Desmaisons** [comment]
Which component? the tree? If so this is not supported by the component.
You will have to fork the project and check how you can achieve what you want with D3.js.

**Comment by Aaron-Coding-Coding** [comment]
thank you
