### ISSUE TITLE
How to change the color of lines linked with a specified node in the tree component?

### ISSUE THREAD

**Issue by Aaron-Coding-Coding** [David-Desmaisons/Vue.D3.tree#19]
hello David.
How to change the color of lines linked with a specified node in the tree component?
just like Hierarchical Edge Bundling component , when the mouse move on a node , the lines color changed. i want the same effect in tree component.
thanks for any suggestions.

**Comment by David-Desmaisons** [comment]
You can use d3.js to achieve that but I am not sure of the interest of such of functionality.
I am not intending it to provide it in this library, as I am not considering this feature as generic enought.
May by then best way would be to fork this project.

**Comment by ghost** [comment]
I have created a solution that i believe solves this problem.

https://github.com/napoleon-commits/vue-d3s-tree

My solution: Added a dynamic CSS computed property and include it in a <component :is="'style'" type="text/css"  Component.

Hope it helps
