### ISSUE TITLE
The svg didn't stop to expanded

### ISSUE THREAD

**Issue by taciomedeiros** [David-Desmaisons/Vue.D3.tree#2]
i use this configs, and make one div that limits the max-height, but the problem continues. Could you help me?
`
<d3tree
              :data="animal.genealogia"
              :type="tree"
              :layout-type="euclidean"
              :duration="5"
              :margin-y="150"
              :zoomable="false">
              </d3tree>`

**Comment by taciomedeiros** [comment]
I see on the example that you put a class on d3tree object with max-height thanks

**Comment by David-Desmaisons** [comment]
@taciomedeiros , by design the component will take all available space respecting the margin value.
This means that you need to specify in the HTML whether max-height or heigth and wether max-width or width.
