### ISSUE TITLE
Tree's height keeps growing for no reason

### ISSUE THREAD

**Issue by Wenzel** [David-Desmaisons/Vue.D3.tree#21]
Hi !

I tried to install and use your component today in my application.
I copy pasted the example provided in the `README`, and the result was ... **quite surprising**.

In fact the generated tree **kept growing in size** and become **bigger** and **bigger** !
There was no way to stop him.

I made a video, if that helps you understand the situation:
https://drive.google.com/file/d/1OTzopXsKPNuztpMzi07iGbHpUOvbT4GC/view?usp=sharing

![screenshot from 2018-08-07 17-40-24](https://user-images.githubusercontent.com/964610/43782897-0d8f341e-9a69-11e8-9c5d-ab2441e70274.png)

Thanks !

**Comment by David-Desmaisons** [comment]
Hello @Wenzel , your component should have a max-height and max-width.

**Comment by David-Desmaisons** [comment]
I just update the documentation with this restriction.

**Comment by Wenzel** [comment]
Hi @David-Desmaisons ,
thank you for quickly looking at my issue and updating the documentation.

I tried again by setting a parent `<div id="vued3tree">`, and assigning it an `height` and `width`:
https://github.com/Wenzel/bug_vued3tree/blob/master/src/components/HelloWorld.vue#L33

But it still doesn't work.
You can see that the CSS is applied:
![screenshot from 2018-08-08 13-08-38](https://user-images.githubusercontent.com/964610/43831272-3b1a59ec-9b0c-11e8-9df9-c30d9fb9b58f.png)
And the size keeps increasing:
![screenshot from 2018-08-08 13-09-22](https://user-images.githubusercontent.com/964610/43831300-57d46f1e-9b0c-11e8-952b-0b623e5c8d26.png)



I don't understand what i'm doing wrong here ?
I created a repo for you to reproduce the issue:
https://github.com/Wenzel/bug_vued3tree

It's a simple `vuejs` project with webpack.
the `tree` is initialized in the `HelloWorld.vue` component.

Thank you for your time.

**Comment by David-Desmaisons** [comment]
Assign width:100% and height:100% to the tree component

**Comment by Wenzel** [comment]
I tried multiple things:
setting the size on the `tree` class:
~~~CSS
.tree {
    width: 100%;
    height: 100%;
}
~~~
doesn't work

setting it on the `svg` generated HTML element:
~~~CSS
svg {
    width: 100%;
    height: 100%;
}
~~~
same result

How do select the `<tree>` component with a CSS selector, as it doesn't exist when the HTML is generated, and the content is replaced by a `<svg>` element ?

I'm sorry for my lack of skills in `VueJS` and `CSS`, totally new to both of them.

Thanks.

**Comment by David-Desmaisons** [comment]
Use:

```HTML
<tree :data="tree" :node-text="name" layoutType="circular" class="tree">
```
```CSS
.tree {
    width: 100%;
    height: 100%;
}
```
If this not resolves the problem, create a webpackbin or something similar so I can check,thanks

**Comment by Wenzel** [comment]
It didn't solve my problem:
![screenshot from 2018-08-08 17-01-49](https://user-images.githubusercontent.com/964610/43841917-e08f3cba-9b2c-11e8-83e7-1a6459a870e2.png)

> create a webpackbin or something similar so I can check,thanks

I created a dedicated repo on Github: https://github.com/Wenzel/bug_vued3tree
all you have to do is clone, `npm install` and `npm run dev`
Is that okay ?
I'm not familiar with `webpackbin` :/

Thank you.

**Comment by David-Desmaisons** [comment]
Last try:

```HTML
<div id="container">
<tree :data="tree" :node-text="name" layoutType="circular" class="tree">
<\div>
```
```CSS
.tree {
    width: 100%;
    height: 100%;
}
.container{
    width: 500px;
    height: 500px;;
}
```
If this does not solve, I don't have time to clone your repo and check it, so you will have to share a live demo if you want me to look at it.

**Comment by Wenzel** [comment]
It worked !
thank you for your time @David-Desmaisons.
