### ISSUE TITLE
How to insert nodes dynamically when a father node is clicked ?

### ISSUE THREAD

**Issue by Wenzel** [David-Desmaisons/Vue.D3.tree#23]
Hi @David-Desmaisons ,

I was wondering how it could be possible to insert new nodes dynamically (fetched from an external resource, like a `GraphQL` endpoint), when the root node is being `clicked`.

So far, I tried the following:
~~~HTML
    <tree :data="tree" node-text="name" class="tree" v-on:clicked="onClicked">
    </tree>
~~~

~~~Javascript
  methods: {
    onClicked: function (event) {
      alert('Bonjour ' + this.tree.name + ' !')
      var child = {
        name: 'child01'
      }
      event.data.children.push(child)
    }
  }
~~~

And the data is indeed updated:
![screenshot from 2018-08-09 11-42-06](https://user-images.githubusercontent.com/964610/43888092-51202fe2-9bc9-11e8-8a77-11aa9babf803.png)

And reflected on the Component tree attribute:
![screenshot from 2018-08-09 11-42-53](https://user-images.githubusercontent.com/964610/43888141-757bf484-9bc9-11e8-8924-50dcd96af4c6.png)

-> So Is it a simple _refresh_ problem ?
-> Can I use your component to insert dynamical data into it, or should i gather all the data from the beginning ?

Thanks David !

**Comment by Wenzel** [comment]
I find this similar issue in the closed ones: https://github.com/David-Desmaisons/Vue.D3.tree/issues/15

But i doesn't help me much here.

**Comment by David-Desmaisons** [comment]
Correct in  version 3.6.0.
