### ISSUE TITLE
Display issues with dynamic update

### ISSUE THREAD

**Issue by Wenzel** [David-Desmaisons/Vue.D3.tree#24]
Hi @David-Desmaisons ,

Thanks to your latest update, I was able to display my filesystem with your component:
![tree](https://user-images.githubusercontent.com/964610/44049640-5683acf8-9f3d-11e8-97ad-ede499feff5f.png)

However, these modifications brought new issues in the display:
- when i click on a node, and add my `children` nodes dynamically, the entire tree is being redrawned.
It's a bit confusing in terms of display. Is there a way to only expand the node I have just clicked instead ?
- since the entire tree is being redrawned, it doesn't save the collapsed nodes state, and all the nodes which were previously expanded are displayed again. 

You can find more details in the following video:
https://drive.google.com/file/d/10OqXoBLWu0foB8Qf6Zz5cEERVEGf0vWF/view?usp=sharing

Thank you

**Comment by David-Desmaisons** [comment]
Hello @Wenzel,
See the updated Readme: you have to use the identifier props to identify the nodes.
You can use check an example here: [Vue.D3.tree/example/tree/App.vue](https://github.com/David-Desmaisons/Vue.D3.tree/blob/master/example/tree/App.vue)
