### ISSUE TITLE
Incorrect docs re: 'zoomable' propery

### ISSUE THREAD

**Issue by michaelfitzhavey** [David-Desmaisons/Vue.D3.tree#26]
The [readme](https://github.com/David-Desmaisons/Vue.D3.tree#properties-1) says that `zoomable` is defaulted to `true` but that seems incorrect?

https://github.com/David-Desmaisons/Vue.D3.tree/blob/master/src/Tree.vue#L61

- thanks a bunch for this component!

**Comment by David-Desmaisons** [comment]
Thanks!
Corrected
