### ISSUE TITLE
create a tree when data is from server

### ISSUE THREAD

**Issue by noninyo** [David-Desmaisons/Vue.D3.tree#3]
Hi,

I write this code. when the tree is defined hardcoded it works greate but when getting the tree data from the server the svg high and width is 0
I attach example for the code:

[example.vue.txt](https://github.com/David-Desmaisons/Vue.D3.tree/files/1151027/example.vue.txt)

Thanks,

**Comment by David-Desmaisons** [comment]
@noninyo , set explicity a width and height to the component

**Comment by noninyo** [comment]
Hi David,

Thanks for you quick replay! 
You can see in the example I set tree_style:
`.tree_style {
		height: 600px;
		width: 100%;
	}`
and I change the width explicitly but it didn't help.
the div get the style but the svg still remain with height and width 0

**Comment by David-Desmaisons** [comment]
I am seeing in your example  that tree component comes with directive: `v-if="showTree"` it seems that showTree is not defined i you component

**Comment by noninyo** [comment]
Sorry you correct, In some point I tried to add it so the tag will be render only after I get the treeData but I remove it because it didn't help

**Comment by David-Desmaisons** [comment]
Did you check the value of the data returned by the server? Did you verify with vue debug tool that thy are set to the treeData props? If you did you try to set the same props with this data with a timeout to try to reproduce without server?

**Comment by noninyo** [comment]
yes, and yes 
![image](https://user-images.githubusercontent.com/10042849/28268622-a399694e-6b07-11e7-8812-d20ac6f18863.png)

how can I check the last?
I am returning the same data as your example so the server return the data very very quickly

**Comment by David-Desmaisons** [comment]
To check the last you can implement a setTimeout( fillTreeData, 5000); where fillTreeData is a function that will set the treeData with the given data.

**Comment by noninyo** [comment]
Still not working :/

**Comment by David-Desmaisons** [comment]
Could you create a jsfiddle?

**Comment by noninyo** [comment]
Hi,

I tried, this is my first time :)
I hope it is ok

https://jsfiddle.net/noninyo/3edq80b8/#&togetherjs=wDAl72R2Gv

**Comment by noninyo** [comment]
Hi David,
Did you have time to look at this? or did you find something that I can do differently? 
Thanks

**Comment by David-Desmaisons** [comment]
@noninyo I did take a look but your jsfiddle is broken since you are trying to require the component in the browser.

**Comment by noninyo** [comment]
Do you know how can I import vued3tree because it seems it can't import the tree component

**Comment by David-Desmaisons** [comment]
@noninyo you can use webpack to build a js file that can be used in the browser

**Comment by noninyo** [comment]
I mean in  the jsfiddle

**Comment by yulinyige** [comment]
I have the same problem, finaly, I found that, tree node can't contain v-show or v-if command. 
即: 不能被 v-show 或 v-if 指令包含着.
