### ISSUE TITLE
error h.transition

### ISSUE THREAD

**Issue by octadv** [David-Desmaisons/Vue.D3.tree#31]
Hi 
i know a previous ticket was opened about this, but was close without explanation. 
I have the same issue.
i'm using yarn.

![screen shot 2018-10-14 at 1 21 19 pm](https://user-images.githubusercontent.com/27001029/46913270-1351f000-cfb4-11e8-85c8-341a6df430aa.png)

**Comment by octadv** [comment]
you can inspect the error here https://fontain.io/tree

**Comment by octadv** [comment]
`<template>
  <div id="container">
  <tree :data="tree" :node-text="name" layoutType="circular" class="tree"></tree></div>
</template>

<script>
import {tree} from 'vued3tree'

export default {
  components: {
    tree
  },
  data() {
    return {
      tree: {
        name: "father",
        children:[{
          name: "son1",
          children:[ {name: "grandson"}, {name: "grandson2"}]
        },{
          name: "son2",
          children:[ {name: "grandson3"}, {name: "grandson4"}]
        }]
      }
    }
  }
}

</script>

<style >
.tree {
    width: 100%;
    height: 100%;
}
.container{
    width: 500px;
    height: 500px;;
}
</style>
`

**Comment by David-Desmaisons** [comment]
Could you share what was the problem to avoid someone else open a similar issue later, and so on?

**Comment by jjstobbe** [comment]
I had the same problem. Seems to be some sort of yarn issue. I installed it normally using `npm install` and re-ran my project and it worked fine. For whatever reason, just using `yarn add vued3tree` doesn't work.
