### ISSUE TITLE
Yarn

### ISSUE THREAD

**Issue by xserber** [David-Desmaisons/Vue.D3.tree#33]
Hi David, are you planning to add support install package for yarn?

**Comment by xserber** [comment]
After installing the package through yarn, it does not work. Errors occur "h.transition". If install through npm, package correct work.

**Comment by David-Desmaisons** [comment]
Could you share the complete scenario and the callstack of the error please?

**Comment by xserber** [comment]
https://github.com/David-Desmaisons/Vue.D3.tree/issues/31
In this release, demo errors and mentions yarn.

**Comment by Lexanimus** [comment]
Found a solution for using vued3tree with Yarn: https://github.com/d3/d3-selection/issues/185

Steps to solve:
1. Add to `package.json`:
```
    "resolutions": {
        "d3-selection": "1.3.0"
    }
```
2. Remove `yarn.lock`
3. Run `yarn`

**Comment by David-Desmaisons** [comment]
@Lexanimus thanks for documenting this work-around.
