### ISSUE TITLE
why my tree renders very slow? 

### ISSUE THREAD

**Issue by xinyu7git** [David-Desmaisons/Vue.D3.tree#34]
my tree renders very slow. after flush page , it will cost 1-2s to render. 
Do you know why? 

![image](https://user-images.githubusercontent.com/3701997/50521297-f1bacc00-0aff-11e9-9c0c-1882e5ce66ea.png)

render finish: 
![image](https://user-images.githubusercontent.com/3701997/50521215-938de900-0aff-11e9-8db7-67e362095824.png)

**Comment by xinyu7git** [comment]
> 1. Set a fixed height to your component
> 2. change the duration property to 0

I have tried, but not work.    my codes: 
<div style="width: 100%; height: 500px; overflow: hidden;">
                <tree :data="treeData" node-text="name" :type="treeCfg.type" :marginX="treeCfg.marginX" :marginY="treeCfg.marginY" :duration="0">
                </tree>
 </div>

**Comment by xinyu7git** [comment]
<div style="width: 100%; height: 400px; overflow: hidden;">
                <tree :data="treeData" node-text="name" :type="treeCfg.type" :marginX="treeCfg.marginX" :marginY="treeCfg.marginY" :duration="0">
                </tree>
            </div>

**Comment by KurosakiRei** [comment]
> > 1. Set a fixed height to your component
> > 2. change the duration property to 0
> 
> I have tried, but not work. my codes: ![image](https://user-images.githubusercontent.com/3701997/50533361-08463f00-0b63-11e9-8e49-ac51b29cab26.png)

I know my reply is probably too late, but I want to provide a solution for the people who encounter the same issue after. You can try to use the inline-CSS in your "tree" element. 
For example, `<tree :data="tree" style="height: 100vh"> `
