### ISSUE TITLE
Collapse tree after the second level

### ISSUE THREAD

**Issue by jpettina** [David-Desmaisons/Vue.D3.tree#35]
Hello! I need to show the collapsed tree from the second level onwards. I found this function of d3 in an example that does what I need:

> root.children.forEach (collapse);

(Link: https://bl.ocks.org/d3noob/43a860bc0024792f8803bba8ca0d5ecd)
Is there a particular function in vued3tree to be able to show the tree the way I need it?
Thank you!

**Comment by David-Desmaisons** [comment]
Use collapseAll method as documented in the readme.
