### ISSUE TITLE
node Radius vs text

### ISSUE THREAD

**Issue by akhchan99** [David-Desmaisons/Vue.D3.tree#38]
On the demo, change the radius of the node doesn't take effect reactively (new radius only updated when the tree is collapsed then expanded.

And when the radius is large (like 10 in the demo), it covered the Text, are there anyway to adjust the spacing between the node and text.

**Comment by David-Desmaisons** [comment]
1) Currently radius is reactive
2) Use nodeTextMagin and leafTextMargin props to adjust margin
