### ISSUE TITLE
Looks amazing

### ISSUE THREAD

**Issue by nicolasvahidzein** [David-Desmaisons/Vue.D3.tree#4]
Hello David, i haven't started using your plugin yet but it looks fantastic. Do you have a live demo i can see in action?

Eventually i would love to use this to create a company structure that is dynamic based on people's job titles and hierarchy.

**Comment by David-Desmaisons** [comment]
Hello @nicolasvahidzein , I will provide it.

**Comment by nicolasvahidzein** [comment]
Oh hello again :) Thank you buddy.

**Comment by nicolasvahidzein** [comment]
Just checking in to see if you had time for the demo link. Thank you David.

**Comment by nicolasvahidzein** [comment]
David?

**Comment by David-Desmaisons** [comment]
Hello @nicolasvahidzein , I am currently dedicating my free time to the [Neutronium](https://github.com/NeutroniumCore/Neutronium) project. I don't know yet exactly when I will have free time to work on Vue.D3.tree.

**Comment by nicolasvahidzein** [comment]
Hello david, i totally understand but there must have been a misunderstanding, i'm just talking about something simple like a jsfiddle. Not a website you need to setup or anything. Just a simple use case.

**Comment by David-Desmaisons** [comment]
Added Live demo:

https://david-desmaisons.github.io/Vue.D3.tree/tree.html

https://david-desmaisons.github.io/Vue.D3.tree/hierarchicalEdgeBundling.html
