### ISSUE TITLE
Is it possible to create a contextmenu?

### ISSUE THREAD

**Issue by heliomsolivas** [David-Desmaisons/Vue.D3.tree#50]
Hi, I have to do some actions in each node, like remove/rename node, actually is it possible to add contextmenu?

**Comment by David-Desmaisons** [comment]
Hi @heliomsolivas , this is not currently possible, but this is something I want to provide. The main idea: provide a slotfor context menu.

**Comment by David-Desmaisons** [comment]
Use the "popUp" slot release in version v5.1.0.
