### ISSUE TITLE
can't access the tree object

### ISSUE THREAD

**Issue by paohaijiao** [David-Desmaisons/Vue.D3.tree#52]
hi david , 
       i have use he command "npm install vued3tree" and   import {tree} from 'vued3tree' in my project(iwant to embed this tree js to my program) 
but the componnet can't identify the tree , could you help me how to resolve this error ?
![d3](https://user-images.githubusercontent.com/13718051/65759503-ae07f800-e14d-11e9-9f62-ed88d506c2c2.png)

**Comment by David-Desmaisons** [comment]
Why do you mean by "can't identify the tree "?
What kind of error did you get?

**Comment by paohaijiao** [comment]
you can see the picture , i have been import the tree from vued3tree, but the  error as bel
![111](https://user-images.githubusercontent.com/13718051/65772580-14504300-e16d-11e9-9f75-a8e3aef4e343.png)
low

**Comment by David-Desmaisons** [comment]
Try `npm install vued3tree` again.
Make sure it works and that the correspoding folder has been created in the node-modules folder

**Comment by paohaijiao** [comment]
the vued3tree folder has been exists my project , but it still not work 
![Uploading 123.png…]()

**Comment by paohaijiao** [comment]
resolved , i have been place wrong folder,thanks
