### ISSUE TITLE
Slot Node is not working

### ISSUE THREAD

**Issue by mquijom** [David-Desmaisons/Vue.D3.tree#53]
Why does slot `node` is not working ? 
Is there any wrong in my code? 

`<tree :data="tree" style="height: 100vh" @clickedText="showDetails">
      <div slot="node" slot-scope="data">{{data.name}}: {{data.gender}}</div>
</tree>`

**Comment by David-Desmaisons** [comment]
@mquijom node slot is rendered in a svg context so you should return svg dom element as documented in the read.me.
https://developer.mozilla.org/en-US/docs/Web/SVG/Element
So div is ont valid. You can try text element
