### ISSUE TITLE
How to style only the paths with children?

### ISSUE THREAD

**Issue by rrrichard** [David-Desmaisons/Vue.D3.tree#55]
Been trying to generate a tree style that looks like this where only the path with children gets colored red 
![Screenshot 2019-10-10 at 15 04 13](https://user-images.githubusercontent.com/31552377/66576627-f53fb100-eb6f-11e9-8eae-ae6794231523.png)

I'm trying to use this example of slot node to color the path but I am unable to isolate the paths that have children. Also how do I access the d path coordinates that is generated?
![Screenshot 2019-10-10 at 14 51 15](https://user-images.githubusercontent.com/31552377/66575919-b6f5c200-eb6e-11e9-93bb-6a9a1b02f54e.png)

**Comment by David-Desmaisons** [comment]
@rrrichard the link part of the svg is drawn by the component without possibility of customization.

I will have to think at an API to hiligth a path but I am not what I could be.

**Comment by rrrichard** [comment]
@David-Desmaisons no worries, thank you.
