### ISSUE TITLE
How to extend custom behavior

### ISSUE THREAD

**Issue by JavaMrYang** [David-Desmaisons/Vue.D3.tree#58]
Do you have any detail examples

**Comment by David-Desmaisons** [comment]
I am not sure of what you are expecting here. What kind of example would you like to see? Do you have a specific doubt?

**Comment by JavaMrYang** [comment]
I don't quite understand the example of that behavior. 
![image](https://user-images.githubusercontent.com/30564116/69505236-ccc71700-0f63-11ea-8a7c-3e9555c5f809.png)

**Comment by David-Desmaisons** [comment]
1) Check https://alligator.io/vuejs/renderless-behavior-slots/

2) This behavior will toggle the state of the node between collapse and expanded when clicling on it.

**Comment by JavaMrYang** [comment]
ok，thank you
