### ISSUE TITLE
issues with big data sets

### ISSUE THREAD

**Issue by G3z** [David-Desmaisons/Vue.D3.tree#6]
Hello I'm trying to use your library to draw a tree of 9.2k+ nodes, this is what I think could be improved:
- nodes tends to overlap when they are many and the container is small: I believe nodes are positioned relative to the canvas size, it would be better if nodes could have some fixed spacing, or at least zoom the graphics, not names.
![schermata 2017-08-10 alle 16 17 15](https://user-images.githubusercontent.com/875086/29174907-f458080c-7de7-11e7-95d8-506aa0dca8d6.png)
- nodes are all open by default: it would be nice to set a max number of open nodes (1000 would be a good default) or read an `open:false` on the nodes to decide if children should be drawn

thank you

**Comment by David-Desmaisons** [comment]
Hello @G3z , thanks for your feedback and suggestion

1) For the overlap mention, did you try the `zoomable` props and if so why was it not satisfactory?
2) This is an interesting suggestion, I like the open property more than a max number of nodes since it will be hard to decide which  nodes to show. It will be a good idea also to make this open prop reactive.
3) Could you share your data as a JSON so I can play around with your data?

**Comment by G3z** [comment]
1. the problem with zooming is that everything just gets bigger or smaller proportionally (dots lines and text should stay the same size only move further apart), so you'll see the above graph bigger. negative margine works better (because drawing size gets bigger than svg size)
2. 👍
3. I'll clean the personal data and share it with you to do some tests asap
4. after tinkering with your lib i noticed min/max zooming is hard coded, using a prop would be better, don't you think ?

**Comment by G3z** [comment]
[data.json.zip](https://github.com/David-Desmaisons/Vue.D3.tree/files/1220171/data.json.zip)
this is a json of 9239 nested accountsand this is the unzoomed result
![schermata 2017-08-13 alle 03 14 46](https://user-images.githubusercontent.com/875086/29245282-a2c29bf2-7fd5-11e7-81a2-0a9c34ac9ec5.png)
in a 1108x900 svg,
how can i help ?

**Comment by David-Desmaisons** [comment]
1. Understood, I played around with another type of zoom where the geometry were re-calculated some time ago. This waht we need here. There maybe have a commit somewhere in the history of this repo with such a code.
2. Ok
3. Thanks.
4) This is a good sugestion I will provide

**Comment by G3z** [comment]
I think i've found a simple trick to avoid overlapping:
currently you are setting the canvas size with [cluster_size](https://github.com/d3/d3-hierarchy/blob/master/README.md#cluster_size) but it is possible to specify the [node size](https://github.com/d3/d3-hierarchy/blob/master/README.md#cluster_size)
```javascript
...
this.layout.size(this.internaldata.tree, size, this.margin, this.maxTextLenght)
.nodeSize([15, 200]); // add this = height:15, width:200px
...
```

**Comment by elendirx** [comment]
Any update on this?

**Comment by David-Desmaisons** [comment]
@G3z could you detail better your proposal, or create a PR?
Thanks

**Comment by David-Desmaisons** [comment]
@G3z version 4.1.0 introduces min and max zoom props as well as a "rescaling" zoom.
This correct problem 1 and 4 that you mentioned.
