### ISSUE TITLE
How to use the "identifier" props?

### ISSUE THREAD

**Issue by Yamei-Tu** [David-Desmaisons/Vue.D3.tree#62]
Hi David, I need to update the tree dynamically and required to use the "identifier" according to the documentation,  could you please give me more explanation about it? Thanks a lot !!!

**Comment by David-Desmaisons** [comment]
I depends do you need to refresh the reload the tree at some point?
If so, you should  worry about it and return a unique identifier of the node. Something like:

```js
 function getId (node) {
    return node.id;
 }
```
