### ISSUE TITLE
Is it possible to have multiple parent nodes for a given child node?

### ISSUE THREAD

**Issue by armaandhull** [David-Desmaisons/Vue.D3.tree#67]
@David-Desmaisons 
I have been able to use vued3tree for use cases where I have 1 parent node and multiple child nodes, and it works great. Now I have a use case where there are multiple parent nodes for a given child node and I'm wondering if it's possible to render the relationship using vued3tree?

**Comment by David-Desmaisons** [comment]
No, it is not possible. 
If so that would not be a tree.
