### ISSUE TITLE
[Firefox 55.0] Tree nodes do not have dots for expanding and retracting

### ISSUE THREAD

**Issue by Claus1** [David-Desmaisons/Vue.D3.tree#8]
It seems the current version has the subject error.
![image 2](https://user-images.githubusercontent.com/1247062/30494517-ab622f54-9a72-11e7-8189-ae71a012789c.png)

**Comment by David-Desmaisons** [comment]
Which Browser? I think this is an edge/IE issue

**Comment by Claus1** [comment]
Firefox 55.03 (the latest) has the problem. Chrome does not.

**Comment by LennartOlsen** [comment]
Its also present on Egde, although in the example from blocks ;
https://bl.ocks.org/mbostock/4339083
It works nicely in Egde (have not tested on Firefox), both d3tree and the blocks example work in Chrome

**Comment by Claus1** [comment]
It is really weird, https://bl.ocks.org/mbostock/4339083 works with dots in Firefox, but d3tree example not.
May be the referenced app uses previous version d3tree?

**Comment by LennartOlsen** [comment]
@Claus1 you are absolutely right

**Comment by jakub-wisniewski** [comment]
So, how shall we fix that?

**Comment by David-Desmaisons** [comment]
@jakub-wisniewski I will review the PR this week. In IE, I think this a browser limittation.

**Comment by David-Desmaisons** [comment]
Corrected by PR #13
