### ISSUE TITLE
[Vue warn]: Error in nextTick: "TypeError: Cannot read properties of undefined (reading 'x')"

### ISSUE THREAD

**Issue by Doclassif** [David-Desmaisons/Vue.D3.tree#82]
[Vue warn]: Error in nextTick: "TypeError: Cannot read properties of undefined (reading 'x')"

**Comment by pcloth** [comment]
@Doclassif I also encountered it, can you tell me how to solve it?

**Comment by pcloth** [comment]
Just add an `identifier` property
