### ISSUE TITLE
vertical layout?

### ISSUE THREAD

**Issue by ilijaveselica** [David-Desmaisons/Vue.D3.tree#9]
Is there an easy workaround to create vertical layout?

**Comment by David-Desmaisons** [comment]
I am not sure what you are trying to do, but you can try to apply CSS transforamtion to the component.

**Comment by ilijaveselica** [comment]
I want to have tree displayed in vertical orientation, similar like this https://bl.ocks.org/mbostock/999346

**Comment by kenokenobingo** [comment]
Is vertical layout still planned?

**Comment by David-Desmaisons** [comment]
@kenokenobingo yes. I will provide it soon

**Comment by David-Desmaisons** [comment]
Implemented in version 4.0.0
